export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_COMMENTS_SUCCESS = 'UPDATE_COMMENTS_SUCCESS';

//Live Chat
export const LOAD_CLIENT_2_TRAINER_CHAT_SUCCESS = 'LOAD_CLIENT_2_TRAINER_CHAT_SUCCESS';
export const SEND_CLIENT_2_TRAINER_CHAT_MESSAGE_SUCCESS = 'SEND_CLIENT_2_TRAINER_CHAT_MESSAGE_SUCCESS';

export const LOAD_CLIENT_2_DOCTOR_CHAT_SUCCESS = 'LOAD_CLIENT_2_DOCTOR_CHAT_SUCCESS';
export const SEND_CLIENT_2_DOCTOR_CHAT_MESSAGE_SUCCESS = 'SEND_CLIENT_2_DOCTOR_CHAT_MESSAGE_SUCCESS';

export const LOAD_TRAINER_2_DOCTOR_CHAT_SUCCESS = 'LOAD_TRAINER_2_DOCTOR_CHAT_SUCCESS';
export const SEND_TRAINER_2_DOCTOR_CHAT_MESSAGE_SUCCESS = 'SEND_TRAINER_2_DOCTOR_CHAT_MESSAGE_SUCCESS';

//Task Manager
export const LOAD_MONDAY_TASKS_SUCCESS = 'LOAD_MONDAY_TASKS_SUCCESS';
export const ADD_MONDAY_TASKS_SUCCESS = 'ADD_MONDAY_TASKS_SUCCESS';
export const DELETE_MONDAY_TASKS_SUCCESS = 'DELETE_MONDAY_TASKS_SUCCESS';

export const LOAD_TUESDAY_TASKS_SUCCESS = 'LOAD_TUESDAY_TASKS_SUCCESS';
export const ADD_TUESDAY_TASKS_SUCCESS = 'ADD_TUESDAY_TASKS_SUCCESS';
export const DELETE_TUESDAY_TASKS_SUCCESS = 'DELETE_TUESDAY_TASKS_SUCCESS';

export const LOAD_WEDNESDAY_TASKS_SUCCESS = 'LOAD_WEDNESDAY_TASKS_SUCCESS';
export const ADD_WEDNESDAY_TASKS_SUCCESS = 'ADD_WEDNESDAY_TASKS_SUCCESS';
export const DELETE_WEDNESDAY_TASKS_SUCCESS = 'DELETE_WEDNESDAY_TASKS_SUCCESS';

export const LOAD_THURSDAY_TASKS_SUCCESS = 'LOAD_THURSDAY_TASKS_SUCCESS';
export const ADD_THURSDAY_TASKS_SUCCESS = 'ADD_THURSDAY_TASKS_SUCCESS';
export const DELETE_THURSDAY_TASKS_SUCCESS = 'DELETE_THURSDAY_TASKS_SUCCESS';

export const LOAD_FRIDAY_TASKS_SUCCESS = 'LOAD_FRIDAY_TASKS_SUCCESS';
export const ADD_FRIDAY_TASKS_SUCCESS = 'ADD_FRIDAY_TASKS_SUCCESS';
export const DELETE_FRIDAY_TASKS_SUCCESS = 'DELETE_FRIDAY_TASKS_SUCCESS';

//WeekGoal
export const LOAD_WEEK_GOAL_SUCCESS = 'LOAD_WEEK_GOAL_SUCCESS';
export const CHANGE_WEEK_GOAL_SUCCESS = 'CHANGE_WEEK_GOAL_SUCCESS';